import express from 'express';
import helmet from 'helmet';
import cors from 'cors';
import compression from 'compression';
import morgan from 'morgan';
import auditRoutes from './routes/audit.routes';
const app=express();
app.use(express.json());
app.use(cors());
app.use(helmet());
app.use(compression());
app.use(morgan('combined'));
app.use('/api/audit',auditRoutes);
app.get('/health',(_,res)=>res.json({status:'UP'}));
export default app;
